#!/bin/bash

truncate -s0 ~/.bitcoinmonstercore/debug.log
sleep 5
truncate -s0 ~/.genixcore/debug.log
truncate -s0 ~/.genixcore2/debug.log
truncate -s0 ~/.genixcore3/debug.log
truncate -s0 ~/.genixcore4/debug.log
truncate -s0 ~/.genixcore5/debug.log
truncate -s0 ~/.genixcore6/debug.log
truncate -s0 ~/.genixcore7/debug.log
truncate -s0 ~/.genixcore8/debug.log
truncate -s0 ~/.genixcore9/debug.log
sleep 5
truncate -s0 ~/.gobytecore/debug.log
truncate -s0 ~/.gobytecore2/debug.log
truncate -s0 ~/.gobytecore3/debug.log
truncate -s0 ~/.gobytecore4/debug.log
truncate -s0 ~/.gobytecore5/debug.log
truncate -s0 ~/.gobytecore6/debug.log
truncate -s0 ~/.gobytecore7/debug.log
truncate -s0 ~/.gobytecore8/debug.log
truncate -s0 ~/.gobytecore9/debug.log
truncate -s0 ~/.gobytecore10/debug.log
sleep 5
truncate -s0 ~/.harvestcore/debug.log
truncate -s0 ~/.harvestcore2/debug.log
truncate -s0 ~/.harvestcore3/debug.log
truncate -s0 ~/.harvestcore4/debug.log
truncate -s0 ~/.harvestcore5/debug.log
truncate -s0 ~/.harvestcore6/debug.log
truncate -s0 ~/.harvestcore7/debug.log
sleep 5
truncate -s0 ~/.innovacore/debug.log
sleep 5
truncate -s0 ~/.konjungatecore/debug.log
truncate -s0 ~/.konjungatecore2/debug.log
truncate -s0 ~/.konjungatecore3/debug.log
truncate -s0 ~/.konjungatecore4/debug.log
truncate -s0 ~/.konjungatecore5/debug.log
truncate -s0 ~/.konjungatecore6/debug.log
truncate -s0 ~/.konjungatecore7/debug.log
truncate -s0 ~/.konjungatecore8/debug.log
truncate -s0 ~/.konjungatecore9/debug.log
truncate -s0 ~/.konjungatecore10/debug.log
truncate -s0 ~/.konjungatecore11/debug.log
truncate -s0 ~/.konjungatecore12/debug.log
truncate -s0 ~/.konjungatecore13/debug.log
sleep 5
truncate -s0 ~/.metrix/debug.log
truncate -s0 ~/.metrix2/debug.log
truncate -s0 ~/.metrix3/debug.log
truncate -s0 ~/.metrix4/debug.log
truncate -s0 ~/.metrix5/debug.log
truncate -s0 ~/.metrix6/debug.log
truncate -s0 ~/.metrix7/debug.log
truncate -s0 ~/.metrix8/debug.log
truncate -s0 ~/.metrix9/debug.log
truncate -s0 ~/.metrix10/debug.log
truncate -s0 ~/.metrix11/debug.log
truncate -s0 ~/.metrix12/debug.log
truncate -s0 ~/.metrix13/debug.log
truncate -s0 ~/.metrix14/debug.log
truncate -s0 ~/.metrix15/debug.log
truncate -s0 ~/.metrix16/debug.log
truncate -s0 ~/.metrix17/debug.log
truncate -s0 ~/.metrix18/debug.log
truncate -s0 ~/.metrix19/debug.log
truncate -s0 ~/.metrix20/debug.log
truncate -s0 ~/.metrix21/debug.log
truncate -s0 ~/.metrix22/debug.log
truncate -s0 ~/.metrix23/debug.log
truncate -s0 ~/.metrix24/debug.log
truncate -s0 ~/.metrix25/debug.log
truncate -s0 ~/.metrix26/debug.log
truncate -s0 ~/.metrix27/debug.log
truncate -s0 ~/.metrix28/debug.log
truncate -s0 ~/.metrix29/debug.log
truncate -s0 ~/.metrix30/debug.log
truncate -s0 ~/.metrix31/debug.log
truncate -s0 ~/.metrix32/debug.log
truncate -s0 ~/.metrix33/debug.log
truncate -s0 ~/.metrix34/debug.log
truncate -s0 ~/.metrix35/debug.log
truncate -s0 ~/.metrix36/debug.log
truncate -s0 ~/.metrix37/debug.log
truncate -s0 ~/.metrix38/debug.log
truncate -s0 ~/.metrix39/debug.log
truncate -s0 ~/.metrix40/debug.log
truncate -s0 ~/.metrix41/debug.log
truncate -s0 ~/.metrix42/debug.log
truncate -s0 ~/.metrix43/debug.log
truncate -s0 ~/.metrix44/debug.log
truncate -s0 ~/.metrix45/debug.log
truncate -s0 ~/.metrix46/debug.log
truncate -s0 ~/.metrix47/debug.log
truncate -s0 ~/.metrix48/debug.log
truncate -s0 ~/.metrix49/debug.log
truncate -s0 ~/.metrix50/debug.log
truncate -s0 ~/.metrix51/debug.log
truncate -s0 ~/.metrix52/debug.log
truncate -s0 ~/.metrix53/debug.log
truncate -s0 ~/.metrix54/debug.log
truncate -s0 ~/.metrix55/debug.log
truncate -s0 ~/.metrix56/debug.log
truncate -s0 ~/.metrix57/debug.log
sleep 5
truncate -s0 ~/.mktcoin/debug.log
truncate -s0 ~/.mktcoin2/debug.log
truncate -s0 ~/.mktcoin3/debug.log
truncate -s0 ~/.mktcoin4/debug.log
truncate -s0 ~/.mktcoin5/debug.log
truncate -s0 ~/.mktcoin6/debug.log
truncate -s0 ~/.mktcoin7/debug.log
truncate -s0 ~/.mktcoin8/debug.log
truncate -s0 ~/.mktcoin9/debug.log
truncate -s0 ~/.mktcoin10/debug.log
truncate -s0 ~/.mktcoin11/debug.log
truncate -s0 ~/.mktcoin12/debug.log
truncate -s0 ~/.mktcoin13/debug.log
truncate -s0 ~/.mktcoin14/debug.log
truncate -s0 ~/.mktcoin15/debug.log
truncate -s0 ~/.mktcoin16/debug.log
truncate -s0 ~/.mktcoin17/debug.log
truncate -s0 ~/.mktcoin18/debug.log
truncate -s0 ~/.mktcoin19/debug.log
truncate -s0 ~/.mktcoin20/debug.log
truncate -s0 ~/.mktcoin21/debug.log
truncate -s0 ~/.mktcoin22/debug.log
sleep 5
truncate -s0 ~/.MoneyByte/debug.log
sleep 5
truncate -s0 ~/.rupayacore/debug.log
truncate -s0 ~/.rupayacore2/debug.log
truncate -s0 ~/.rupayacore3/debug.log
truncate -s0 ~/.rupayacore4/debug.log
truncate -s0 ~/.rupayacore5/debug.log
sleep 5
truncate -s0 ~/.sap/debug.log
truncate -s0 ~/.sap2/debug.log
truncate -s0 ~/.sap3/debug.log
truncate -s0 ~/.sap4/debug.log
truncate -s0 ~/.sap5/debug.log
sleep 5
truncate -s0 ~/.stashcore/debug.log
