#!/bin/bash

sleep 5
truncate -s0 ~/.innovacore1/debug.log
truncate -s0 ~/.innovacore2/debug.log
truncate -s0 ~/.innovacore3/debug.log
truncate -s0 ~/.innovacore4/debug.log
truncate -s0 ~/.innovacore5/debug.log
truncate -s0 ~/.innovacore6/debug.log
truncate -s0 ~/.innovacore7/debug.log
truncate -s0 ~/.innovacore8/debug.log
truncate -s0 ~/.innovacore9/debug.log
truncate -s0 ~/.innovacore10/debug.log
truncate -s0 ~/.innovacore11/debug.log
truncate -s0 ~/.innovacore12/debug.log
truncate -s0 ~/.innovacore13/debug.log
truncate -s0 ~/.innovacore14/debug.log
truncate -s0 ~/.innovacore15/debug.log
truncate -s0 ~/.innovacore16/debug.log
truncate -s0 ~/.innovacore17/debug.log
truncate -s0 ~/.innovacore18/debug.log
truncate -s0 ~/.innovacore19/debug.log
truncate -s0 ~/.innovacore20/debug.log
truncate -s0 ~/.innovacore21/debug.log
truncate -s0 ~/.innovacore22/debug.log
truncate -s0 ~/.innovacore23/debug.log
truncate -s0 ~/.innovacore24/debug.log
truncate -s0 ~/.innovacore25/debug.log
truncate -s0 ~/.innovacore26/debug.log
truncate -s0 ~/.innovacore27/debug.log
truncate -s0 ~/.innovacore28/debug.log
truncate -s0 ~/.innovacore29/debug.log
truncate -s0 ~/.innovacore30/debug.log
truncate -s0 ~/.innovacore31/debug.log
truncate -s0 ~/.innovacore32/debug.log
truncate -s0 ~/.innovacore33/debug.log
truncate -s0 ~/.innovacore34/debug.log
truncate -s0 ~/.innovacore35/debug.log
truncate -s0 ~/.innovacore36/debug.log
truncate -s0 ~/.innovacore37/debug.log
truncate -s0 ~/.innovacore38/debug.log
truncate -s0 ~/.innovacore39/debug.log
truncate -s0 ~/.innovacore40/debug.log
truncate -s0 ~/.innovacore41/debug.log
truncate -s0 ~/.innovacore42/debug.log
truncate -s0 ~/.innovacore43/debug.log
truncate -s0 ~/.innovacore44/debug.log
truncate -s0 ~/.innovacore45/debug.log
truncate -s0 ~/.innovacore46/debug.log
truncate -s0 ~/.innovacore47/debug.log
truncate -s0 ~/.innovacore48/debug.log
truncate -s0 ~/.innovacore49/debug.log
truncate -s0 ~/.innovacore50/debug.log
truncate -s0 ~/.innovacore51/debug.log
truncate -s0 ~/.innovacore52/debug.log
truncate -s0 ~/.innovacore53/debug.log
truncate -s0 ~/.innovacore54/debug.log
truncate -s0 ~/.innovacore55/debug.log
truncate -s0 ~/.innovacore56/debug.log
truncate -s0 ~/.innovacore57/debug.log
truncate -s0 ~/.innovacore58/debug.log
truncate -s0 ~/.innovacore59/debug.log
truncate -s0 ~/.innovacore60/debug.log
truncate -s0 ~/.innovacore61/debug.log
truncate -s0 ~/.innovacore62/debug.log
truncate -s0 ~/.innovacore63/debug.log
truncate -s0 ~/.innovacore64/debug.log
truncate -s0 ~/.innovacore65/debug.log
truncate -s0 ~/.innovacore66/debug.log
truncate -s0 ~/.innovacore67/debug.log
truncate -s0 ~/.innovacore68/debug.log
truncate -s0 ~/.innovacore69/debug.log
truncate -s0 ~/.innovacore70/debug.log
truncate -s0 ~/.innovacore71/debug.log
truncate -s0 ~/.innovacore72/debug.log
truncate -s0 ~/.innovacore73/debug.log
truncate -s0 ~/.innovacore74/debug.log
truncate -s0 ~/.innovacore75/debug.log
truncate -s0 ~/.innovacore76/debug.log
truncate -s0 ~/.innovacore77/debug.log
sleep 5
truncate -s0 ~/.SagaCoin/debug.log
truncate -s0 ~/.SagaCoin2/debug.log
truncate -s0 ~/.SagaCoin3/debug.log
truncate -s0 ~/.SagaCoin4/debug.log
truncate -s0 ~/.SagaCoin5/debug.log
truncate -s0 ~/.SagaCoin6/debug.log
truncate -s0 ~/.SagaCoin7/debug.log
truncate -s0 ~/.SagaCoin8/debug.log
truncate -s0 ~/.SagaCoin9/debug.log
truncate -s0 ~/.SagaCoin10/debug.log
truncate -s0 ~/.SagaCoin11/debug.log
truncate -s0 ~/.SagaCoin12/debug.log
truncate -s0 ~/.SagaCoin13/debug.log
truncate -s0 ~/.SagaCoin14/debug.log
truncate -s0 ~/.SagaCoin15/debug.log
