#!/bin/bash

sleep 5
truncate -s0 ~/.monkey_mn1/debug.log
truncate -s0 ~/.monkey_mn2/debug.log
truncate -s0 ~/.monkey_sai1/debug.log
truncate -s0 ~/.monkey_sai2/debug.log
truncate -s0 ~/.monkey_sai3/debug.log
truncate -s0 ~/.monkey_sai4/debug.log
sleep 5
truncate -s0 ~/.OPCoinX/debug.log
truncate -s0 ~/.OPCoinX2/debug.log
truncate -s0 ~/.OPCoinX3/debug.log
truncate -s0 ~/.OPCoinX4/debug.log
truncate -s0 ~/.OPCoinX5/debug.log
truncate -s0 ~/.OPCoinX6/debug.log
truncate -s0 ~/.OPCoinX7/debug.log
sleep 5
truncate -s0 ~/.innovacore1/debug.log
truncate -s0 ~/.innovacore2/debug.log
truncate -s0 ~/.innovacore3/debug.log
truncate -s0 ~/.innovacore4/debug.log
truncate -s0 ~/.innovacore5/debug.log
truncate -s0 ~/.innovacore6/debug.log
truncate -s0 ~/.innovacore7/debug.log
truncate -s0 ~/.innovacore8/debug.log
truncate -s0 ~/.innovacore9/debug.log
truncate -s0 ~/.innovacore10/debug.log
truncate -s0 ~/.innovacore11/debug.log
truncate -s0 ~/.innovacore12/debug.log
truncate -s0 ~/.innovacore13/debug.log
truncate -s0 ~/.innovacore14/debug.log
truncate -s0 ~/.innovacore15/debug.log
truncate -s0 ~/.innovacore16/debug.log
truncate -s0 ~/.innovacore17/debug.log
truncate -s0 ~/.innovacore18/debug.log
truncate -s0 ~/.innovacore19/debug.log
truncate -s0 ~/.innovacore20/debug.log
truncate -s0 ~/.innovacore21/debug.log
truncate -s0 ~/.innovacore22/debug.log
truncate -s0 ~/.innovacore23/debug.log
truncate -s0 ~/.innovacore24/debug.log
truncate -s0 ~/.innovacore25/debug.log
truncate -s0 ~/.innovacore31/debug.log
truncate -s0 ~/.innovacore32/debug.log
truncate -s0 ~/.innovacore33/debug.log
truncate -s0 ~/.innovacore34/debug.log
truncate -s0 ~/.innovacore35/debug.log
truncate -s0 ~/.innovacore36/debug.log
sleep 5
truncate -s0 ~/.SagaCoin/debug.log
truncate -s0 ~/.SagaCoin2/debug.log
truncate -s0 ~/.SagaCoin3/debug.log
truncate -s0 ~/.SagaCoin4/debug.log
truncate -s0 ~/.SagaCoin5/debug.log
truncate -s0 ~/.SagaCoin6/debug.log
truncate -s0 ~/.SagaCoin7/debug.log
truncate -s0 ~/.SagaCoin8/debug.log
truncate -s0 ~/.SagaCoin9/debug.log
truncate -s0 ~/.SagaCoin10/debug.log
truncate -s0 ~/.SagaCoin11/debug.log
truncate -s0 ~/.SagaCoin12/debug.log
truncate -s0 ~/.SagaCoin13/debug.log
truncate -s0 ~/.SagaCoin14/debug.log
truncate -s0 ~/.SagaCoin15/debug.log
truncate -s0 ~/.SagaCoin16/debug.log
truncate -s0 ~/.SagaCoin17/debug.log
truncate -s0 ~/.SagaCoin18/debug.log
truncate -s0 ~/.SagaCoin19/debug.log
truncate -s0 ~/.SagaCoin20/debug.log
truncate -s0 ~/.SagaCoin21/debug.log
truncate -s0 ~/.SagaCoin22/debug.log
truncate -s0 ~/.SagaCoin23/debug.log
truncate -s0 ~/.SagaCoin24/debug.log
truncate -s0 ~/.SagaCoin25/debug.log
truncate -s0 ~/.SagaCoin26/debug.log
truncate -s0 ~/.SagaCoin27/debug.log
truncate -s0 ~/.SagaCoin28/debug.log
truncate -s0 ~/.SagaCoin29/debug.log
truncate -s0 ~/.SagaCoin30/debug.log
truncate -s0 ~/.SagaCoin31/debug.log
truncate -s0 ~/.SagaCoin32/debug.log
truncate -s0 ~/.SagaCoin33/debug.log
truncate -s0 ~/.SagaCoin34/debug.log
truncate -s0 ~/.SagaCoin35/debug.log
truncate -s0 ~/.SagaCoin36/debug.log
truncate -s0 ~/.SagaCoin37/debug.log
truncate -s0 ~/.SagaCoin38/debug.log
