#!/bin/bash

truncate -s0 ~/.bitcoinmonstercore/debug.log
sleep 5
truncate -s0 ~/.esbcoin/debug.log
sleep 5
truncate -s0 ~/.genixcore/debug.log
truncate -s0 ~/.genixcore2/debug.log
truncate -s0 ~/.genixcore3/debug.log
truncate -s0 ~/.genixcore4/debug.log
truncate -s0 ~/.genixcore5/debug.log
truncate -s0 ~/.genixcore6/debug.log
sleep 5
truncate -s0 ~/.gobytecore/debug.log
truncate -s0 ~/.gobytecore2/debug.log
truncate -s0 ~/.gobytecore3/debug.log
truncate -s0 ~/.gobytecore4/debug.log
truncate -s0 ~/.gobytecore5/debug.log
truncate -s0 ~/.gobytecore6/debug.log
truncate -s0 ~/.gobytecore7/debug.log
truncate -s0 ~/.gobytecore8/debug.log
truncate -s0 ~/.gobytecore9/debug.log
truncate -s0 ~/.gobytecore10/debug.log
truncate -s0 ~/.gobytecore11/debug.log
sleep 5
truncate -s0 ~/.innovacore/debug.log
truncate -s0 ~/.innovacore2/debug.log
truncate -s0 ~/.innovacore3/debug.log
truncate -s0 ~/.innovacore4/debug.log
truncate -s0 ~/.innovacore5/debug.log
truncate -s0 ~/.innovacore6/debug.log
truncate -s0 ~/.innovacore7/debug.log
truncate -s0 ~/.innovacore8/debug.log
truncate -s0 ~/.innovacore9/debug.log
truncate -s0 ~/.innovacore10/debug.log
truncate -s0 ~/.innovacore11/debug.log
truncate -s0 ~/.innovacore12/debug.log
truncate -s0 ~/.innovacore13/debug.log
truncate -s0 ~/.innovacore14/debug.log
truncate -s0 ~/.innovacore15/debug.log
truncate -s0 ~/.innovacore16/debug.log
truncate -s0 ~/.innovacore17/debug.log
truncate -s0 ~/.innovacore18/debug.log
truncate -s0 ~/.innovacore19/debug.log
truncate -s0 ~/.innovacore20/debug.log
truncate -s0 ~/.innovacore21/debug.log
truncate -s0 ~/.innovacore22/debug.log
truncate -s0 ~/.innovacore23/debug.log
truncate -s0 ~/.innovacore24/debug.log
truncate -s0 ~/.innovacore25/debug.log
sleep 5
truncate -s0 ~/.jemcash/debug.log
truncate -s0 ~/.jemcash2/debug.log
truncate -s0 ~/.jemcash3/debug.log
truncate -s0 ~/.jemcash4/debug.log
truncate -s0 ~/.jemcash5/debug.log
truncate -s0 ~/.jemcash6/debug.log
sleep 5
truncate -s0 ~/.Konjungate/debug.log
sleep 5
truncate -s0 ~/.konjungatecore/debug.log
truncate -s0 ~/.konjungatecore2/debug.log
truncate -s0 ~/.konjungatecore3/debug.log
truncate -s0 ~/.konjungatecore4/debug.log
truncate -s0 ~/.konjungatecore5/debug.log
truncate -s0 ~/.konjungatecore6/debug.log
truncate -s0 ~/.konjungatecore7/debug.log
truncate -s0 ~/.konjungatecore8/debug.log
truncate -s0 ~/.konjungatecore9/debug.log
truncate -s0 ~/.konjungatecore10/debug.log
truncate -s0 ~/.konjungatecore11/debug.log
truncate -s0 ~/.konjungatecore12/debug.log
truncate -s0 ~/.konjungatecore13/debug.log
sleep 5
truncate -s0 ~/.metrix/debug.log
truncate -s0 ~/.metrix2/debug.log
truncate -s0 ~/.metrix3/debug.log
truncate -s0 ~/.metrix4/debug.log
truncate -s0 ~/.metrix5/debug.log
truncate -s0 ~/.metrix6/debug.log
truncate -s0 ~/.metrix7/debug.log
truncate -s0 ~/.metrix8/debug.log
truncate -s0 ~/.metrix9/debug.log
truncate -s0 ~/.metrix10/debug.log
truncate -s0 ~/.metrix11/debug.log
truncate -s0 ~/.metrix12/debug.log
truncate -s0 ~/.metrix13/debug.log
truncate -s0 ~/.metrix14/debug.log
truncate -s0 ~/.metrix15/debug.log
truncate -s0 ~/.metrix16/debug.log
truncate -s0 ~/.metrix17/debug.log
sleep 5
truncate -s0 ~/.mktcoin/debug.log
truncate -s0 ~/.mktcoin2/debug.log
truncate -s0 ~/.mktcoin3/debug.log
truncate -s0 ~/.mktcoin4/debug.log
truncate -s0 ~/.mktcoin5/debug.log
truncate -s0 ~/.mktcoin6/debug.log
truncate -s0 ~/.mktcoin7/debug.log
truncate -s0 ~/.mktcoin8/debug.log
truncate -s0 ~/.mktcoin9/debug.log
truncate -s0 ~/.mktcoin10/debug.log
truncate -s0 ~/.mktcoin11/debug.log
truncate -s0 ~/.mktcoin12/debug.log
truncate -s0 ~/.mktcoin13/debug.log
truncate -s0 ~/.mktcoin14/debug.log
truncate -s0 ~/.mktcoin15/debug.log
truncate -s0 ~/.mktcoin16/debug.log
truncate -s0 ~/.mktcoin17/debug.log
truncate -s0 ~/.mktcoin18/debug.log
truncate -s0 ~/.mktcoin19/debug.log
truncate -s0 ~/.mktcoin20/debug.log
truncate -s0 ~/.mktcoin21/debug.log
sleep 5
truncate -s0 ~/.MoneyByte/debug.log
sleep 5
truncate -s0 ~/.monkey_wave1/debug.log
truncate -s0 ~/.monkey_wave2/debug.log
truncate -s0 ~/.monkey_wave3/debug.log
truncate -s0 ~/.monkey_wave4/debug.log
truncate -s0 ~/.monkey_wave5/debug.log
truncate -s0 ~/.monkey_wave6/debug.log
truncate -s0 ~/.monkey_wave7/debug.log
truncate -s0 ~/.monkey_wave8/debug.log
truncate -s0 ~/.monkey_wave9/debug.log
truncate -s0 ~/.monkey_wave10/debug.log
truncate -s0 ~/.monkey_wave11/debug.log
truncate -s0 ~/.monkey_wave12/debug.log
truncate -s0 ~/.monkey_wave13/debug.log
truncate -s0 ~/.monkey_wave14/debug.log
truncate -s0 ~/.monkey_wave15/debug.log
truncate -s0 ~/.monkey_waveman301/debug.log
truncate -s0 ~/.monkey_waveman302/debug.log
truncate -s0 ~/.monkey_waveman303/debug.log
truncate -s0 ~/.monkey_waveman304/debug.log
truncate -s0 ~/.monkey_waveman305/debug.log
truncate -s0 ~/.monkey_waveman306/debug.log
truncate -s0 ~/.monkey_waveman307/debug.log
truncate -s0 ~/.monkey_waveman308/debug.log
truncate -s0 ~/.monkey_waveman309/debug.log
truncate -s0 ~/.monkey_waveman3010/debug.log
truncate -s0 ~/.monkey_waveman3011/debug.log
truncate -s0 ~/.monkey_waveman3012/debug.log
truncate -s0 ~/.monkey_waveman3013/debug.log
truncate -s0 ~/.monkey_waveman3014/debug.log
truncate -s0 ~/.monkey_waveman3015/debug.log
truncate -s0 ~/.monkey_waveman3016/debug.log
truncate -s0 ~/.monkey_waveman3017/debug.log
truncate -s0 ~/.monkey_waveman3018/debug.log
truncate -s0 ~/.monkey_waveman3019/debug.log
truncate -s0 ~/.monkey_waveman3020/debug.log
truncate -s0 ~/.monkey_waveman3021/debug.log
truncate -s0 ~/.monkey_waveman3022/debug.log
truncate -s0 ~/.monkey_waveman3023/debug.log
truncate -s0 ~/.monkey_waveman3024/debug.log
truncate -s0 ~/.monkey_waveman3025/debug.log
truncate -s0 ~/.monkey_waveman3026/debug.log
truncate -s0 ~/.monkey_waveman3027/debug.log
truncate -s0 ~/.monkey_waveman3028/debug.log
truncate -s0 ~/.monkey_waveman3029/debug.log
truncate -s0 ~/.monkey_waveman3030/debug.log
truncate -s0 ~/.monkey_waveman3031/debug.log
truncate -s0 ~/.monkey_waveman3032/debug.log
truncate -s0 ~/.monkey_waveman3033/debug.log
truncate -s0 ~/.monkey_waveman3034/debug.log
truncate -s0 ~/.monkey_waveman3035/debug.log
sleep 5
truncate -s0 ~/.rupayacore/debug.log
sleep 5
truncate -s0 ~/.xsncore/debug.log
